security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: app_accueil
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        # accès public
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/accueil, roles: PUBLIC_ACCESS }
        - { path: ^/api/recherche, roles: PUBLIC_ACCESS }
        - { path: ^/mentions, roles: PUBLIC_ACCESS }
        - { path: ^/css, roles: PUBLIC_ACCESS }
        - { path: ^/js, roles: PUBLIC_ACCESS }
        - { path: ^/images, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }

        # accès réservé admin
        - { path: ^/admin, roles: ROLE_ADMIN }

        # accès réservé utilisateur normal
        - { path: ^/reservation, roles: ROLE_USER }
        - { path: ^/historique, roles: ROLE_USER }
        - { path: ^/mes-reservations, roles: ROLE_USER }

        # par défaut, il faut être connecté (ROLE_USER)
        - { path: ^/, roles: ROLE_USER }